export * from './actors.service';
import { ActorsService } from './actors.service';
export * from './breakdown.service';
import { BreakdownService } from './breakdown.service';
export * from './milestones.service';
import { MilestonesService } from './milestones.service';
export * from './reasons.service';
import { ReasonsService } from './reasons.service';
export * from './repositories.service';
import { RepositoriesService } from './repositories.service';
export * from './requirementSets.service';
import { RequirementSetsService } from './requirementSets.service';
export * from './requirements.service';
import { RequirementsService } from './requirements.service';
export const APIS = [ActorsService, BreakdownService, MilestonesService, ReasonsService, RepositoriesService, RequirementSetsService, RequirementsService];
