/**
 * LOIN.Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/problemDetails';
import { Requirement } from '../model/requirement';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RequirementsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param repositoryId 
     * @param actors Coma separated list of actors (id) for the context filtering
     * @param reasons Coma separated list of reasons (id) for the context filtering
     * @param breakdown Coma separated list of breakdown items (id) for the context filtering
     * @param milestones Coma separated list of milestones (id) for the context filtering
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepositoryIdRequirementsExportGet(repositoryId: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public apiRepositoryIdRequirementsExportGet(repositoryId: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public apiRepositoryIdRequirementsExportGet(repositoryId: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public apiRepositoryIdRequirementsExportGet(repositoryId: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (repositoryId === null || repositoryId === undefined) {
            throw new Error('Required parameter repositoryId was null or undefined when calling apiRepositoryIdRequirementsExportGet.');
        }





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (actors !== undefined && actors !== null) {
            queryParameters = queryParameters.set('actors', <any>actors);
        }
        if (reasons !== undefined && reasons !== null) {
            queryParameters = queryParameters.set('reasons', <any>reasons);
        }
        if (breakdown !== undefined && breakdown !== null) {
            queryParameters = queryParameters.set('breakdown', <any>breakdown);
        }
        if (milestones !== undefined && milestones !== null) {
            queryParameters = queryParameters.set('milestones', <any>milestones);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/api/${encodeURIComponent(String(repositoryId))}/requirements/export`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param repositoryId 
     * @param select OData select expression
     * @param filter OData filter expression
     * @param orderby OData order-by expression
     * @param skip OData &#x27;skip&#x27; attribute. Usable for paging.
     * @param top OData &#x27;top&#x27; attribute. Usable for paging.
     * @param apply OData &#x27;apply&#x27; attribute. Usable for grouping, aggregations etc.
     * @param actors Coma separated list of actors (id) for the context filtering
     * @param reasons Coma separated list of reasons (id) for the context filtering
     * @param breakdown Coma separated list of breakdown items (id) for the context filtering
     * @param milestones Coma separated list of milestones (id) for the context filtering
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepositoryIdRequirementsGet(repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Requirement>>;
    public apiRepositoryIdRequirementsGet(repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Requirement>>>;
    public apiRepositoryIdRequirementsGet(repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Requirement>>>;
    public apiRepositoryIdRequirementsGet(repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, actors?: string, reasons?: string, breakdown?: string, milestones?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (repositoryId === null || repositoryId === undefined) {
            throw new Error('Required parameter repositoryId was null or undefined when calling apiRepositoryIdRequirementsGet.');
        }











        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (select !== undefined && select !== null) {
            queryParameters = queryParameters.set('$select', <any>select);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('$filter', <any>filter);
        }
        if (orderby !== undefined && orderby !== null) {
            queryParameters = queryParameters.set('$orderby', <any>orderby);
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('$skip', <any>skip);
        }
        if (top !== undefined && top !== null) {
            queryParameters = queryParameters.set('$top', <any>top);
        }
        if (apply !== undefined && apply !== null) {
            queryParameters = queryParameters.set('$apply', <any>apply);
        }
        if (actors !== undefined && actors !== null) {
            queryParameters = queryParameters.set('actors', <any>actors);
        }
        if (reasons !== undefined && reasons !== null) {
            queryParameters = queryParameters.set('reasons', <any>reasons);
        }
        if (breakdown !== undefined && breakdown !== null) {
            queryParameters = queryParameters.set('breakdown', <any>breakdown);
        }
        if (milestones !== undefined && milestones !== null) {
            queryParameters = queryParameters.set('milestones', <any>milestones);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json;odata.metadata=minimal;odata.streaming=true',
            'application/json;odata.metadata=minimal;odata.streaming=false',
            'application/json;odata.metadata=minimal',
            'application/json;odata.metadata=full;odata.streaming=true',
            'application/json;odata.metadata=full;odata.streaming=false',
            'application/json;odata.metadata=full',
            'application/json;odata.metadata=none;odata.streaming=true',
            'application/json;odata.metadata=none;odata.streaming=false',
            'application/json;odata.metadata=none',
            'application/json;odata.streaming=true',
            'application/json;odata.streaming=false',
            'application/json',
            'application/xml',
            'application/prs.odatatestxx-odata',
            'text/plain',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Requirement>>('get',`${this.basePath}/api/${encodeURIComponent(String(repositoryId))}/requirements`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param repositoryId 
     * @param select OData select expression
     * @param filter OData filter expression
     * @param orderby OData order-by expression
     * @param skip OData &#x27;skip&#x27; attribute. Usable for paging.
     * @param top OData &#x27;top&#x27; attribute. Usable for paging.
     * @param apply OData &#x27;apply&#x27; attribute. Usable for grouping, aggregations etc.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepositoryIdRequirementsIdGet(id: number, repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, observe?: 'body', reportProgress?: boolean): Observable<Requirement>;
    public apiRepositoryIdRequirementsIdGet(id: number, repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Requirement>>;
    public apiRepositoryIdRequirementsIdGet(id: number, repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Requirement>>;
    public apiRepositoryIdRequirementsIdGet(id: number, repositoryId: string, select?: string, filter?: string, orderby?: string, skip?: number, top?: number, apply?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiRepositoryIdRequirementsIdGet.');
        }

        if (repositoryId === null || repositoryId === undefined) {
            throw new Error('Required parameter repositoryId was null or undefined when calling apiRepositoryIdRequirementsIdGet.');
        }







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (select !== undefined && select !== null) {
            queryParameters = queryParameters.set('$select', <any>select);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('$filter', <any>filter);
        }
        if (orderby !== undefined && orderby !== null) {
            queryParameters = queryParameters.set('$orderby', <any>orderby);
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('$skip', <any>skip);
        }
        if (top !== undefined && top !== null) {
            queryParameters = queryParameters.set('$top', <any>top);
        }
        if (apply !== undefined && apply !== null) {
            queryParameters = queryParameters.set('$apply', <any>apply);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json;odata.metadata=minimal;odata.streaming=true',
            'application/json;odata.metadata=minimal;odata.streaming=false',
            'application/json;odata.metadata=minimal',
            'application/json;odata.metadata=full;odata.streaming=true',
            'application/json;odata.metadata=full;odata.streaming=false',
            'application/json;odata.metadata=full',
            'application/json;odata.metadata=none;odata.streaming=true',
            'application/json;odata.metadata=none;odata.streaming=false',
            'application/json;odata.metadata=none',
            'application/json;odata.streaming=true',
            'application/json;odata.streaming=false',
            'application/json',
            'application/xml',
            'application/prs.odatatestxx-odata',
            'text/plain',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Requirement>('get',`${this.basePath}/api/${encodeURIComponent(String(repositoryId))}/requirements/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
